title: Draft.dev
description: >
  Learn to Build a Better Technical Blog
permalink: ':categories/:title'
baseurl: "/learn"
url: "https://draft.dev"
twitter: draftdev
default-img: default-img.jpg
social-rss: /feed.xml
authors:
  karl:
    name: Karl Hughes
    twitter: karllhughes
    website: "https://www.karllhughes.com"
    img: "/assets/authors/karl.png"
    bio: "Karl is a former startup CTO and the founder of Draft.dev. He writes about technical blogging and content management."
  alyssa:
    name: Alyssa Shea
  matt:
    name: Matthew Warholak
    website: "https://www.moneyredpill.com/"
    img: "/assets/authors/matt.jpeg"
    bio: "Matt is a Technical Writer and Editor for Technology, Financial Services, and everything in-between. When he's not writing or editing, he's analyzing commodity markets, ideating new ventures, or learning French."
  tola:
    name: Tola Ore-Aruwaji
    website: "https://github.com/thecraftman"
    img: "/assets/authors/tola.jpeg"
    bio: "Tola is an open-source contributor at Chaoss and a technical writer for Draft.dev."
  keanan:
    name: Keanan Koppenhaver
    website: "https://alphaparticle.com/"
    img: "/assets/authors/keanan.jpg"
    bio: "Keanan is the CTO at Alpha Particle where he helps publishers modernize their technology platforms."
  josh:
    name: Josh Alletto
    website: "https://www.linkedin.com/in/josh-alletto/"
    img: "/assets/authors/josh.jpg"
    bio: "Josh is a former educator turned developer with a proven ability to learn quickly and adapt to different roles. He's always looking for a new challenge and a dedicated team to collaborate with."
  piero:
    name: Piero Borrelli
    twitter: borrellidev
    website: "https://pieroborrellidev.medium.com/"
    img: "/assets/authors/piero.jpg"
    bio: "Software developer for the Wi-Fi industry. Burning keyboards with JavaScript code. Talking about the ups and downs of the developer’s life."
  sebastian:
    name: Sebastian Nilsson
    twitter: sebnilsson
    website: "https://sebnilsson.com/"
    img: "/assets/authors/sebastian.jpg"
    bio: "Professional problem-solver, developing great ideas into solutions with value. Focus on Open Source, .NET, JavaScript/TypeScript, Azure, Web, DevOps, Agile & Leadership."
  anastasia:
      name: Anastasia Orlova
      website: "https://www.linkedin.com/in/anastasiaorlova88/"
      img: "/assets/authors/anastasia.jpeg"
      bio: "Full-stack web developer experienced in Ruby on Rails and JavaScript-based programming with a background in retail and social work. Transformed her passion for learning foreign languages and creative writing into programming languages and tech blogging."

# Tracker
analytics: UA-19700764-23 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data", ".idea"]
