title: Draft.dev
description: >
  Learn to Build a Better Technical Blog
permalink: ':title'
baseurl: "/learn"
url: "https://draft.dev"
twitter: draftdev
default-img: default-img.jpg
social-rss: /feed.xml

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "admin/index.html"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"

# Tracker
analytics: UA-19700764-23 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data", ".idea"]
