title: Draft.dev
description: >
  Learn to Build a Better Technical Blog
permalink: ':categories/:title'
baseurl: "/learn"
url: "https://draft.dev"
twitter: draftdev
default-img: default-img.jpg
social-rss: /feed.xml
defaults:
  -
    scope:
      path: "admin/index.html"
    values:
      sitemap: false
authors:
  karl:
    name: Karl Hughes
    twitter: karllhughes
    website: "https://www.karllhughes.com"
    img: "/assets/authors/karl.png"
    bio: "Karl is a former startup CTO and the founder of Draft.dev. He writes about technical blogging and content management."
  chris:
    name: Chris Wolfgang
    twitter: chriswolfgang
    website: "https://chriswolfgang.com/"
    img: "/assets/authors/chris.jpg"
    bio: "Chris Wolfgang is the editor at Draft.dev. She’s been writing and editing for tech for longer than she would care to remember."
  john:
    name: John Gramila
    website: "https://www.linkedin.com/in/jgramila/"
    img: "/assets/authors/john.jpg"
    bio: "John Gramila is a coder and writer living in Chicago, and one of Draft.dev's first authors."
  richard:
    name: Richard White
    website: "https://www.linkedin.com/in/richard-white-b9909511/"
    img: "/assets/authors/richard.png"
    bio: "Richard is a communications expert with over a decade of experience across B2B and B2C. He currently manages marketing content at Draft.dev."
  alyssa:
    name: Alyssa Shea
  matt:
    name: Matthew Warholak
    website: "https://www.moneyredpill.com/"
    img: "/assets/authors/matt.jpeg"
    bio: "Matt is a Technical Writer and Editor for Technology, Financial Services, and everything in-between. When he's not writing or editing, he's analyzing commodity markets, ideating new ventures, or learning French."
  tola:
    name: Tola Ore-Aruwaji
    website: "https://github.com/thecraftman"
    img: "/assets/authors/tola.jpeg"
    bio: "Tola is an open-source contributor at Chaoss and a technical writer for Draft.dev."
  keanan:
    name: Keanan Koppenhaver
    website: "https://alphaparticle.com/"
    img: "/assets/authors/keanan.jpg"
    bio: "Keanan is the CTO at Alpha Particle where he helps publishers modernize their technology platforms."
  josh:
    name: Josh Alletto
    website: "https://www.linkedin.com/in/josh-alletto/"
    img: "/assets/authors/josh.jpg"
    bio: "Josh is a former educator turned developer with a proven ability to learn quickly and adapt to different roles. He's always looking for a new challenge and a dedicated team to collaborate with."
  piero:
    name: Piero Borrelli
    twitter: borrellidev
    website: "https://pieroborrellidev.medium.com/"
    img: "/assets/authors/piero.jpg"
    bio: "Software developer for the Wi-Fi industry. Burning keyboards with JavaScript code. Talking about the ups and downs of the developer’s life."
  sebastian:
    name: Sebastian Nilsson
    twitter: sebnilsson
    website: "https://sebnilsson.com/"
    img: "/assets/authors/sebastian.jpg"
    bio: "Professional problem-solver, developing great ideas into solutions with value. Focus on Open Source, .NET, JavaScript/TypeScript, Azure, Web, DevOps, Agile & Leadership."
  anastasia:
      name: Anastasia Orlova
      website: "https://www.linkedin.com/in/anastasiaorlova88/"
      img: "/assets/authors/anastasia.jpeg"
      bio: "Full-stack web developer experienced in Ruby on Rails and JavaScript-based programming with a background in retail and social work. Transformed her passion for learning foreign languages and creative writing into programming languages and tech blogging."
  amisha:
    name: Amisha Singh
    twitter: Amishasinghrana
    website: "https://asrwritings.com/"
    img: "/assets/authors/amisha.jpg"
    bio: "Amisha has been freelancing for over three years and has worked with clients from all over the world. Working with people with diverse backgrounds has made her understand the importance of diversity in today’s digital world."
  zara:
    name: Zara Cooper
    website: "https://zaracooper.github.io/"
    twitter: Zara__Cooper
    img: "/assets/authors/zara.jpg"
    bio: "Zara Cooper is a software developer who enjoys sharing what she learns with others. She mostly works with Angular, React, Go, and Ruby. Her interests include open source, system design, and technical writing. When she’s got time to spare, she enjoys reading a good book over a cup of hot cocoa."
  ashutosh:
    name: Ashutosh K Singh
    website: "https://github.com/lelouchB"
    twitter: noharashutosh
    img: "/assets/authors/ashutosh.jpg"
    bio: "Ashutosh is a JavaScript developer and a technical writer. He writes about the fundamentals of JavaScript, Node.js, React, and tutorials on building projects in JavaScript and React."
  siddhant:
    name: Siddhant Varma
    website: "https://medium.com/@sid.cd.varma"
    img: "/assets/authors/siddhant.jpg"
    bio: "Siddhant is a full stack JavaScript Developer with experience in ReactJS, Firebase, Angular and NodeJS. He writes for the community to create awareness and knowledge and help the engineering community learn and grow."
  sodeeq:
    name: Sodeeq Elusoji
    twitter: sdktalks
    website: "https://github.com/sdkcodes"
    img: "/assets/authors/sodeeq.jpg"
    bio: "Sodeeq Elusoji is a full-stack software developer, building web applications and writing technical content."
  nicolas:
    name: Nicolas Bohorquez
    twitter: nickmancol
    img: "/assets/authors/nicolas.jpg"
    bio: "Nicolas Bohorquez is a data architect at Merqueo, has been part of development teams in a handful of startups, and has founded three companies in the Americas. He is passionate about the modeling of complexity and the use of data science to improve the world."
  meagan:
    name: Meagan Shelley
    website: "https://www.linkedin.com/in/meaganshelley/"
    img: "/assets/authors/meagan.jpg"
    bio: "Meagan is a professional writer in VA that specializes in content marketing, research, and SEO. If she's not helping people craft their own stories, she's working on some of her own. When she takes time to step away from the laptop, she enjoys hiking, farmer's markets, and occasional thru-hikes."
  matias:
    name: "Matías Hernández"
    website: "https://matiashernandez.dev/"
    img: "/assets/authors/matias.jpg"
    bio: "Matias is a Chilean Software Engineer with 10+ years of experience as a remote frontend dev. His work focuses on the React ecosystem but also experiments beyond that to keep pushing limits. Matias also participates in communities helping others and creating content through writing, podcasting, or courses with egghead.io."

# Tracker
analytics: UA-19700764-23 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data", ".idea"]
