title: Draft Academy
description: > # this means to ignore newlines until "baseurl:"
  Learn to Build a Better Technical Blog
permalink: ':categories/:title'
baseurl: ""
url: "https://learn.draft.dev"
default-img: default-img.jpg
social-rss: /feed.xml

# Tracker
analytics: UA-19700764-24 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "legacy-data", ".idea"]
